/*
 * pharmacy
 * API para administrar una farmacia
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: l22140765@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pharmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * Employe
 */
@JsonPropertyOrder({
  Employe.JSON_PROPERTY_ID_EMPLOYE,
  Employe.JSON_PROPERTY_ID_PHARMACY,
  Employe.JSON_PROPERTY_NAME,
  Employe.JSON_PROPERTY_LAST_NAME,
  Employe.JSON_PROPERTY_PHONE,
  Employe.JSON_PROPERTY_TYPE_EMPLOYE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-04T13:50:12.904429500-06:00[America/Mexico_City]")
public class Employe {
  public static final String JSON_PROPERTY_ID_EMPLOYE = "idEmploye";
  private Integer idEmploye;

  public static final String JSON_PROPERTY_ID_PHARMACY = "idPharmacy";
  private Integer idPharmacy;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  /**
   * Tipo de producto asociado (Cajero, Doctor)
   */
  public enum TypeEmployeEnum {
    CAJERO("Cajero"),
    
    DOCTOR("Doctor");

    private String value;

    TypeEmployeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEmployeEnum fromValue(String value) {
      for (TypeEmployeEnum b : TypeEmployeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE_EMPLOYE = "typeEmploye";
  private TypeEmployeEnum typeEmploye;

  public Employe() { 
  }

  public Employe idEmploye(Integer idEmploye) {
    this.idEmploye = idEmploye;
    return this;
  }

   /**
   * Get idEmploye
   * minimum: 1
   * maximum: 2147483647
   * @return idEmploye
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_ID_EMPLOYE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIdEmploye() {
    return idEmploye;
  }


  @JsonProperty(JSON_PROPERTY_ID_EMPLOYE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdEmploye(Integer idEmploye) {
    this.idEmploye = idEmploye;
  }


  public Employe idPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
    return this;
  }

   /**
   * Llave foranea que referencia ID de la tabla pharmacy
   * minimum: 1
   * maximum: 2147483647
   * @return idPharmacy
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIdPharmacy() {
    return idPharmacy;
  }


  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
  }


  public Employe name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Employe lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Employe phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=10,max=20)
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Employe typeEmploye(TypeEmployeEnum typeEmploye) {
    this.typeEmploye = typeEmploye;
    return this;
  }

   /**
   * Tipo de producto asociado (Cajero, Doctor)
   * @return typeEmploye
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TYPE_EMPLOYE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEmployeEnum getTypeEmploye() {
    return typeEmploye;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_EMPLOYE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeEmploye(TypeEmployeEnum typeEmploye) {
    this.typeEmploye = typeEmploye;
  }


  /**
   * Return true if this employe object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Employe employe = (Employe) o;
    return Objects.equals(this.idEmploye, employe.idEmploye) &&
        Objects.equals(this.idPharmacy, employe.idPharmacy) &&
        Objects.equals(this.name, employe.name) &&
        Objects.equals(this.lastName, employe.lastName) &&
        Objects.equals(this.phone, employe.phone) &&
        Objects.equals(this.typeEmploye, employe.typeEmploye);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idEmploye, idPharmacy, name, lastName, phone, typeEmploye);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Employe {\n");
    sb.append("    idEmploye: ").append(toIndentedString(idEmploye)).append("\n");
    sb.append("    idPharmacy: ").append(toIndentedString(idPharmacy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    typeEmploye: ").append(toIndentedString(typeEmploye)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `idEmploye` to the URL query string
    if (getIdEmploye() != null) {
      joiner.add(String.format("%sidEmploye%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdEmploye()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `idPharmacy` to the URL query string
    if (getIdPharmacy() != null) {
      joiner.add(String.format("%sidPharmacy%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdPharmacy()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format("%slastName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format("%sphone%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPhone()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `typeEmploye` to the URL query string
    if (getTypeEmploye() != null) {
      joiner.add(String.format("%stypeEmploye%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTypeEmploye()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

