/*
 * pharmacy
 * API para administrar una farmacia
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: l22140765@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pharmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * Employee
 */
@JsonPropertyOrder({
  Employee.JSON_PROPERTY_ID_EMPLOYEE,
  Employee.JSON_PROPERTY_ID_PHARMACY,
  Employee.JSON_PROPERTY_NAME,
  Employee.JSON_PROPERTY_LAST_NAME,
  Employee.JSON_PROPERTY_PHONE,
  Employee.JSON_PROPERTY_TYPE_EMPLOYEE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-06T18:47:26.075651800-06:00[America/Mexico_City]")
public class Employee {
  public static final String JSON_PROPERTY_ID_EMPLOYEE = "idEmployee";
  private Integer idEmployee;

  public static final String JSON_PROPERTY_ID_PHARMACY = "idPharmacy";
  private Integer idPharmacy;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  /**
   * Tipo de producto asociado (Cajero, Doctor)
   */
  public enum TypeEmployeeEnum {
    CAJERO("Cajero"),
    
    DOCTOR("Doctor");

    private String value;

    TypeEmployeeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEmployeeEnum fromValue(String value) {
      for (TypeEmployeeEnum b : TypeEmployeeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE_EMPLOYEE = "typeEmployee";
  private TypeEmployeeEnum typeEmployee;

  public Employee() { 
  }

  public Employee idEmployee(Integer idEmployee) {
    this.idEmployee = idEmployee;
    return this;
  }

   /**
   * Get idEmployee
   * minimum: 1
   * maximum: 2147483647
   * @return idEmployee
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_ID_EMPLOYEE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIdEmployee() {
    return idEmployee;
  }


  @JsonProperty(JSON_PROPERTY_ID_EMPLOYEE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdEmployee(Integer idEmployee) {
    this.idEmployee = idEmployee;
  }


  public Employee idPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
    return this;
  }

   /**
   * Llave foranea que referencia ID de la tabla pharmacy
   * minimum: 1
   * maximum: 2147483647
   * @return idPharmacy
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIdPharmacy() {
    return idPharmacy;
  }


  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
  }


  public Employee name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Employee lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Employee phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=10,max=20)
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Employee typeEmployee(TypeEmployeeEnum typeEmployee) {
    this.typeEmployee = typeEmployee;
    return this;
  }

   /**
   * Tipo de producto asociado (Cajero, Doctor)
   * @return typeEmployee
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TYPE_EMPLOYEE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEmployeeEnum getTypeEmployee() {
    return typeEmployee;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_EMPLOYEE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeEmployee(TypeEmployeeEnum typeEmployee) {
    this.typeEmployee = typeEmployee;
  }


  /**
   * Return true if this employee object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Employee employee = (Employee) o;
    return Objects.equals(this.idEmployee, employee.idEmployee) &&
        Objects.equals(this.idPharmacy, employee.idPharmacy) &&
        Objects.equals(this.name, employee.name) &&
        Objects.equals(this.lastName, employee.lastName) &&
        Objects.equals(this.phone, employee.phone) &&
        Objects.equals(this.typeEmployee, employee.typeEmployee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idEmployee, idPharmacy, name, lastName, phone, typeEmployee);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Employee {\n");
    sb.append("    idEmployee: ").append(toIndentedString(idEmployee)).append("\n");
    sb.append("    idPharmacy: ").append(toIndentedString(idPharmacy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    typeEmployee: ").append(toIndentedString(typeEmployee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `idEmployee` to the URL query string
    if (getIdEmployee() != null) {
      joiner.add(String.format("%sidEmployee%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdEmployee()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `idPharmacy` to the URL query string
    if (getIdPharmacy() != null) {
      joiner.add(String.format("%sidPharmacy%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdPharmacy()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format("%slastName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format("%sphone%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPhone()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `typeEmployee` to the URL query string
    if (getTypeEmployee() != null) {
      joiner.add(String.format("%stypeEmployee%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTypeEmployee()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

