/*
 * pharmacy
 * API para administrar una farmacia
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: l22140765@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pharmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;


/**
 * Pharmacy
 */
@JsonPropertyOrder({
  Pharmacy.JSON_PROPERTY_ID_PHARMACY,
  Pharmacy.JSON_PROPERTY_NAME,
  Pharmacy.JSON_PROPERTY_ADDRESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-06T18:47:26.075651800-06:00[America/Mexico_City]")
public class Pharmacy {
  public static final String JSON_PROPERTY_ID_PHARMACY = "idPharmacy";
  private Integer idPharmacy;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public Pharmacy() { 
  }

  public Pharmacy(Integer idPharmacy, String name, String address) {
    this.idPharmacy = idPharmacy;
    this.name = name;
    this.address = address;
  }

  public Pharmacy idPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
    return this;
  }

   /**
   * Get idPharmacy
   * minimum: 1
   * maximum: 2147483647
   * @return idPharmacy
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIdPharmacy() {
    return idPharmacy;
  }


  @JsonProperty(JSON_PROPERTY_ID_PHARMACY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdPharmacy(Integer idPharmacy) {
    this.idPharmacy = idPharmacy;
  }


  public Pharmacy name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=100)
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Pharmacy address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=3,max=254)
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }


  /**
   * Return true if this pharmacy object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pharmacy pharmacy = (Pharmacy) o;
    return Objects.equals(this.idPharmacy, pharmacy.idPharmacy) &&
        Objects.equals(this.name, pharmacy.name) &&
        Objects.equals(this.address, pharmacy.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idPharmacy, name, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pharmacy {\n");
    sb.append("    idPharmacy: ").append(toIndentedString(idPharmacy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `idPharmacy` to the URL query string
    if (getIdPharmacy() != null) {
      joiner.add(String.format("%sidPharmacy%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdPharmacy()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format("%saddress%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

