/*
 * pharmacy
 * API para administrar una farmacia
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: l22140765@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pharmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pharmacy.api.model.SaleProduct;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * Sale
 */
@JsonPropertyOrder({
  Sale.JSON_PROPERTY_SALE_ID,
  Sale.JSON_PROPERTY_SALE_DATE,
  Sale.JSON_PROPERTY_SUB_TOTAL,
  Sale.JSON_PROPERTY_IVA,
  Sale.JSON_PROPERTY_TOTAL,
  Sale.JSON_PROPERTY_PHARMACY_ID,
  Sale.JSON_PROPERTY_EMPLOYE_ID,
  Sale.JSON_PROPERTY_PRODUCTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-06T17:58:46.397555300-06:00[America/Mexico_City]")
public class Sale {
  public static final String JSON_PROPERTY_SALE_ID = "saleId";
  private Integer saleId;

  public static final String JSON_PROPERTY_SALE_DATE = "saleDate";
  private OffsetDateTime saleDate;

  public static final String JSON_PROPERTY_SUB_TOTAL = "subTotal";
  private Double subTotal;

  public static final String JSON_PROPERTY_IVA = "iva";
  private Double iva;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private Double total;

  public static final String JSON_PROPERTY_PHARMACY_ID = "pharmacyId";
  private Integer pharmacyId;

  public static final String JSON_PROPERTY_EMPLOYE_ID = "employeId";
  private Integer employeId;

  public static final String JSON_PROPERTY_PRODUCTS = "products";
  private List<SaleProduct> products = new ArrayList<>();

  public Sale() { 
  }

  public Sale saleId(Integer saleId) {
    this.saleId = saleId;
    return this;
  }

   /**
   * Get saleId
   * minimum: 1
   * maximum: 2147483647
   * @return saleId
  **/
  @jakarta.annotation.Nullable
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_SALE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSaleId() {
    return saleId;
  }


  @JsonProperty(JSON_PROPERTY_SALE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaleId(Integer saleId) {
    this.saleId = saleId;
  }


  public Sale saleDate(OffsetDateTime saleDate) {
    this.saleDate = saleDate;
    return this;
  }

   /**
   * Get saleDate
   * @return saleDate
  **/
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_SALE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getSaleDate() {
    return saleDate;
  }


  @JsonProperty(JSON_PROPERTY_SALE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSaleDate(OffsetDateTime saleDate) {
    this.saleDate = saleDate;
  }


  public Sale subTotal(Double subTotal) {
    this.subTotal = subTotal;
    return this;
  }

   /**
   * Get subTotal
   * @return subTotal
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SUB_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSubTotal() {
    return subTotal;
  }


  @JsonProperty(JSON_PROPERTY_SUB_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubTotal(Double subTotal) {
    this.subTotal = subTotal;
  }


  public Sale iva(Double iva) {
    this.iva = iva;
    return this;
  }

   /**
   * Get iva
   * @return iva
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_IVA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getIva() {
    return iva;
  }


  @JsonProperty(JSON_PROPERTY_IVA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIva(Double iva) {
    this.iva = iva;
  }


  public Sale total(Double total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(Double total) {
    this.total = total;
  }


  public Sale pharmacyId(Integer pharmacyId) {
    this.pharmacyId = pharmacyId;
    return this;
  }

   /**
   * ID de la farmacia donde se realizó la venta
   * minimum: 1
   * maximum: 2147483647
   * @return pharmacyId
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_PHARMACY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPharmacyId() {
    return pharmacyId;
  }


  @JsonProperty(JSON_PROPERTY_PHARMACY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPharmacyId(Integer pharmacyId) {
    this.pharmacyId = pharmacyId;
  }


  public Sale employeId(Integer employeId) {
    this.employeId = employeId;
    return this;
  }

   /**
   * ID del empleado que realizó la venta
   * minimum: 1
   * maximum: 2147483647
   * @return employeId
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Min(1) @Max(2147483647)
  @JsonProperty(JSON_PROPERTY_EMPLOYE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEmployeId() {
    return employeId;
  }


  @JsonProperty(JSON_PROPERTY_EMPLOYE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmployeId(Integer employeId) {
    this.employeId = employeId;
  }


  public Sale products(List<SaleProduct> products) {
    this.products = products;
    return this;
  }

  public Sale addProductsItem(SaleProduct productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SaleProduct> getProducts() {
    return products;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProducts(List<SaleProduct> products) {
    this.products = products;
  }


  /**
   * Return true if this sale object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sale sale = (Sale) o;
    return Objects.equals(this.saleId, sale.saleId) &&
        Objects.equals(this.saleDate, sale.saleDate) &&
        Objects.equals(this.subTotal, sale.subTotal) &&
        Objects.equals(this.iva, sale.iva) &&
        Objects.equals(this.total, sale.total) &&
        Objects.equals(this.pharmacyId, sale.pharmacyId) &&
        Objects.equals(this.employeId, sale.employeId) &&
        Objects.equals(this.products, sale.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleId, saleDate, subTotal, iva, total, pharmacyId, employeId, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sale {\n");
    sb.append("    saleId: ").append(toIndentedString(saleId)).append("\n");
    sb.append("    saleDate: ").append(toIndentedString(saleDate)).append("\n");
    sb.append("    subTotal: ").append(toIndentedString(subTotal)).append("\n");
    sb.append("    iva: ").append(toIndentedString(iva)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    pharmacyId: ").append(toIndentedString(pharmacyId)).append("\n");
    sb.append("    employeId: ").append(toIndentedString(employeId)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");


    if (getSaleId() != null) {
      joiner.add(String.format("%ssaleId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSaleId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getSaleDate() != null) {
      joiner.add(String.format("%ssaleDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSaleDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getSubTotal() != null) {
      joiner.add(String.format("%ssubTotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSubTotal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getIva() != null) {
      joiner.add(String.format("%siva%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIva()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getTotal() != null) {
      joiner.add(String.format("%stotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getPharmacyId() != null) {
      joiner.add(String.format("%spharmacyId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPharmacyId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getEmployeId() != null) {
      joiner.add(String.format("%semployeId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEmployeId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }


    if (getProducts() != null) {
      for (int i = 0; i < getProducts().size(); i++) {
        if (getProducts().get(i) != null) {
          joiner.add(getProducts().get(i).toUrlQueryString(String.format("%sproducts%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

