/*
 * pharmacy
 * API para administrar una farmacia
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: l22140765@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pharmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pharmacy.api.model.SaleProduct;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * Esquema para actualizaciones parciales de una venta
 */
@JsonPropertyOrder({
  SalePatch.JSON_PROPERTY_SALE_DATE,
  SalePatch.JSON_PROPERTY_SUB_TOTAL,
  SalePatch.JSON_PROPERTY_IVA,
  SalePatch.JSON_PROPERTY_TOTAL,
  SalePatch.JSON_PROPERTY_PRODUCTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-06T18:47:26.075651800-06:00[America/Mexico_City]")
public class SalePatch {
  public static final String JSON_PROPERTY_SALE_DATE = "saleDate";
  private OffsetDateTime saleDate;

  public static final String JSON_PROPERTY_SUB_TOTAL = "subTotal";
  private Double subTotal;

  public static final String JSON_PROPERTY_IVA = "iva";
  private Double iva;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private Double total;

  public static final String JSON_PROPERTY_PRODUCTS = "products";
  private List<SaleProduct> products;

  public SalePatch() { 
  }

  public SalePatch saleDate(OffsetDateTime saleDate) {
    this.saleDate = saleDate;
    return this;
  }

   /**
   * Get saleDate
   * @return saleDate
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SALE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSaleDate() {
    return saleDate;
  }


  @JsonProperty(JSON_PROPERTY_SALE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaleDate(OffsetDateTime saleDate) {
    this.saleDate = saleDate;
  }


  public SalePatch subTotal(Double subTotal) {
    this.subTotal = subTotal;
    return this;
  }

   /**
   * Get subTotal
   * @return subTotal
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SUB_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSubTotal() {
    return subTotal;
  }


  @JsonProperty(JSON_PROPERTY_SUB_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubTotal(Double subTotal) {
    this.subTotal = subTotal;
  }


  public SalePatch iva(Double iva) {
    this.iva = iva;
    return this;
  }

   /**
   * Get iva
   * @return iva
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IVA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getIva() {
    return iva;
  }


  @JsonProperty(JSON_PROPERTY_IVA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIva(Double iva) {
    this.iva = iva;
  }


  public SalePatch total(Double total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(Double total) {
    this.total = total;
  }


  public SalePatch products(List<SaleProduct> products) {
    this.products = products;
    return this;
  }

  public SalePatch addProductsItem(SaleProduct productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SaleProduct> getProducts() {
    return products;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProducts(List<SaleProduct> products) {
    this.products = products;
  }


  /**
   * Return true if this salePatch object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalePatch salePatch = (SalePatch) o;
    return Objects.equals(this.saleDate, salePatch.saleDate) &&
        Objects.equals(this.subTotal, salePatch.subTotal) &&
        Objects.equals(this.iva, salePatch.iva) &&
        Objects.equals(this.total, salePatch.total) &&
        Objects.equals(this.products, salePatch.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleDate, subTotal, iva, total, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalePatch {\n");
    sb.append("    saleDate: ").append(toIndentedString(saleDate)).append("\n");
    sb.append("    subTotal: ").append(toIndentedString(subTotal)).append("\n");
    sb.append("    iva: ").append(toIndentedString(iva)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `saleDate` to the URL query string
    if (getSaleDate() != null) {
      joiner.add(String.format("%ssaleDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSaleDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `subTotal` to the URL query string
    if (getSubTotal() != null) {
      joiner.add(String.format("%ssubTotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSubTotal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `iva` to the URL query string
    if (getIva() != null) {
      joiner.add(String.format("%siva%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIva()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format("%stotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `products` to the URL query string
    if (getProducts() != null) {
      for (int i = 0; i < getProducts().size(); i++) {
        if (getProducts().get(i) != null) {
          joiner.add(getProducts().get(i).toUrlQueryString(String.format("%sproducts%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

